### ISSUE TITLE
Allow Fliperoo to re-initialize

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fliparoo#11]
What if we wanted 6 display elements for a wide screen, 4 for a narrower screen, and 2 for mobile? We could use [Breakpoints](http://xoxco.com/projects/code/breakpoints/) to trigger different JS at different widths, but what about screen resizing? Once a display is initialized, it ought to be able to be re-initialized perhaps with different settings such as the count of display elements.

Could we dynamically adapt if new display elements appear/disappear using jQuery's `$.live()` functionality? This way, if any elements get a `display: none`, we'd automatically remove them from the `displayItems` array.

**Comment by sethlbrown** [comment]
@jjeff This issue is blocking #710 on Lullabot.com. Can I have permission for Ardas to do some work on this?

**Comment by jpamental** [comment]
Not sure if it helps, but one thing I found was that reflowing from 4 across to 2 across, 2 deep on smaller screens worked great. So if you are happy with the amount of content and just want it to reflow to an alternate layout, normal responsive media query css works fine.

**Comment by sethlbrown** [comment]
I think the idea here would be to have a different number of items visible
on the screen at different break points rather than simply having it behave
responsibly.

On Thu, Nov 21, 2013 at 8:29 AM, Jason Pamental notifications@github.comwrote:

> Not sure if it helps, but one thing I found was that reflowing from 4
> across to 2 across, 2 deep on smaller screens worked great. So if you are
> happy with the amount of content and just want it to reflow to an alternate
> layout, normal responsive media query css works fine.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Lullabot/fliparoo/issues/11#issuecomment-28993534
> .

## 

Seth Brown
Director of Operations
Lullabot
seth@lullabot.com
c: 970-618-5370
w: 877.585.5226
http://lbt.me/seth

**Comment by jpamental** [comment]
That’s what I figured; just wanted to put the option out there :)

Modernizr also has media query ties in JS - I have some of the code in the demo, but just saw that I didn’t finish wiring that up - so you could use that to pull elements from the DOM with very little effort I think.

(if you’re using Modernizr)

**Comment by AnnMatrosova** [comment]
@sethlbrown @jpamental as I understand the issue was to reinitialize fliparoo with different displayCount upon window resize. Because if we just hide items with css (using media query) we will never see some logos at all. 

Now in <a href="https://github.com/Lullabot/lullabot.com/pull/710">#710</a> displayCount depends on window size when page loads for the first time. So, when a visitor loads the page he will see proper result. The problem only happens when a visitor resizes the window (no page load) - a rare case.

The simple solution is just hide with CSS if we don't care much that some logos will never be visible. It will work properly upon next page reload. Most people are not very picky - they will not resize window much and then sit and watch for all logos :)

The more complex solution is to reinitialize Fliparoo upon resizing just like we do this on page load if we want to fight for an absolutely proper behavior.

No Modernizr is needed in both cases.

**Comment by sethlbrown** [comment]
@ann-ardas I'm going to agree with your analysis that when people resize
the screen without reloading the page, they're not going to sit there and
wait to see if all the logos appear, so I think simply hiding the logos
that no longer fit on the screen is adequate. Also, if we use the random
Fliparoo configuration, won't all logos show up in all spots eventually?

On Fri, Nov 22, 2013 at 4:47 AM, ann-ardas notifications@github.com wrote:

> @sethlbrown https://github.com/sethlbrown @jpamentalhttps://github.com/jpamentalas I understand the issue was to reinitialize fliparoo with different
> displayCount upon window resize. Because if we just hide items with css
> (using media query) we will never see some logos at all.
> 
> Now in #710 https://github.com/Lullabot/lullabot.com/pull/710displayCount depends on window size when page loads for the first time. So,
> when a visitor loads the page he will see proper result. The problem only
> happens when a visitor resizes the window (no page load) - a rare case.
> 
> The simple solution is just hide with CSS if we don't care much that some
> logos will never be visible. It will work properly upon next page reload.
> Most people are not very picky - they will not resize window much and then
> sit and watch for all logos :)
> 
> The more complex solution is to reinitialize Fliparoo upon resizing just
> like we do this on page load if we want to fight for an absolutely proper
> behavior.
> 
> No Modernizr is needed in both cases.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Lullabot/fliparoo/issues/11#issuecomment-29066989
> .

## 

Seth Brown
Director of Operations
Lullabot
seth@lullabot.com
c: 970-618-5370
w: 877.585.5226
http://lbt.me/seth

**Comment by AnnMatrosova** [comment]
@sethlbrown I've tested the behavior when random option is true and some logos are hidden with css. And in this case we really get all logos shown up.
